# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be50f9ada5445c3bc07b649345fd9ef52dea2d51d9ef5fa1a519b7c566b186a376879586f71d6dd4a3b4c44802a0ffab75da087fb4829e720399cfdff71db07f

test:
  secret_key_base: 9d524708cabe8957a7b8a6df952aafda80a95f04f3350a9bbf5e4bae17e789671f09af336bd4115ee34f87c84fc935e4411e29e063e1fcb9fb77e89f752d60cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
